[project]
name = "mcpdemo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain>=1.0.8",
    "langchain-groq>=1.0.1",
    "langchain-mcp-adapters>=0.1.13",
    "langgraph>=1.0.3",
    "mcp>=1.22.0",
]
